gbm.loop <- function(loops = 10, # the number of loops required, integer
                     savecsv = T, # save the variances in simple & extended format
                     grids,         # explantory data to predict to. Import with (e.g.)
                     # read.csv and specify object name.
                     samples,  # explanatory and response variables to predict from.
                     # Keep col names short, no odd characters, starting numerals or terminal periods
                     # Spaces may be converted to periods in directory names, underscores won't.
                     # Can be a subset
                     expvar,               # list of column numbers of explanatory variables in
                     # 'samples', expected e.g. c(1,35,67,etc.). No default
                     resvar,               # column number of response variable (e.g. CPUE) in
                     # samples. Expected, e.g. 12. No default. Column name should be species name
                     tc = c(2),            # permutations of tree complexity allowed, can be a
                     # vector with the largest sized number no larger than the number of
                     # explanatory variables e.g. c(2,7), or a list of 2 single numbers or vectors,
                     # the first to be passed to the binary BRT, the second to the Gaussian, e.g.
                     # tc = list(c(2,6), 2) or list(6, c(2,6))
                     lr = c(0.01),   # permutations of learning rate allowed. Can be a
                     # vector or a list of 2 single numbers or vectors, the first to be passed to
                     # the binary BRT, the second to the Gaussian, e.g.
                     # lr = list(c(0.01,0.02),0.0001) or list(0.01,c(0.001, 0.0005))
                     bf = 0.5,             # permutations of bag fraction allowed, can be single
                     # number, vector or list, per tc and lr
                     ZI = "CHECK",         # are data zero-inflated? TRUE/FALSE/"CHECK".
                     # TRUE: delta BRT, log-normalised Gaus, reverse log-norm and bias corrected.
                     # FALSE: do Gaussian only, no log-normalisation.
                     # CHECK: Tests data for you. Default is TRUE.
                     simp = TRUE,          # try simplfying best BRTs?
                     gridslat = 2,         # column number for latitude in 'grids'
                     gridslon = 1,         # column number for longitude in 'grids'
                     cols = grey.colors(1,1,1), # barplot colour vector. Assignment in order of
                     # explanatory variables. Default 1*white: white bars black borders. '1*' repeats
                     linesfiles = F,   # save individual line plots' data as csv's?
                     savegbm = F,       # save gbm objects and make available in environment after running? Open with load("Bin_Best_Model")
                     varint = F,        # calculate variable interactions? Default:TRUE, FALSE
                     # for error "contrasts can be applied only to factors with 2 or more levels"
                     map = F,           # save abundance map png files?
                     mapshape = NULL,      # set coast shapefile, else downloaded and autogenerated
                     RSB = TRUE,           # run Unrepresentativeness surface builder?
                     BnW = F,           # repeat maps in black and white e.g. for print journals
                     alerts = T,        # play sounds to mark progress steps
                     pngtype = "cairo-png",# filetype for png files, alternatively try "quartz"
                     ...) {
  var.df <- grids[,c(gridslon, gridslat)] # create df with just lat & longs
  # label columns colnames
  for (i in 1:loops) { # loop through all gbm.autos
    dir.create(paste("./", i, sep = ""))
    setwd(paste("./", i, sep = ""))
    # typical gbm.auto run, w/ rsb csvs no maps.
    # simp F for now but probably should for representativeness
    gbm.auto(grids = grids,
             samples = samples,
             expvar = expvar,
             resvar = resvar,
             tc = tc,
             lr = lr,
             bf = bf,
             ZI = ZI,
             simp = simp,
             gridslat = gridslat,
             gridslon = gridslon,
             cols = cols,
             linesfiles = linesfiles,
             savegbm = savegbm,
             varint = varint,
             map = map,
             mapshape = mapshape,
             RSB = RSB,
             BnW = BnW,
             alerts = alerts,
             pngtype = pngtype,
             ...) # accept other gbm.auto values than these basics. Should maybe make all values be samples = samples
   predtmp <- read.csv("Abundance_Preds_only.csv") # temp container for latest preds
   var.df <- cbind(var.df, predtmp[,3]) # cbind preds to existing lat/longs or other preds
   # label column colnames
    setwd("../")
  } # close i loop & go to the next one

  Variances <- rep(NA, times = length(var.df[,1])) # create blank vector as long as loops
  var.df <- cbind(var.df, Variances) # add blank vector to final column of var.df

  for (j in 1:length(var.df[,1])) { # loop through each row of var.df AKA predabunds AKA grids
    var.df[j,Variances] <- var(var.df[j, (3:(2 + loops))]) # to that row of the Variances column,
    # add the variance of the other rows, not inc lat & lon
  } #close j loop

  if (savecsv) {write.csv(var.df, file = "VarAll.csv")
                write.csv(var.df[,c(1,2,Variances)], file = "VarOnly.csv")}

  # add mapping option maybe with log sclae like RSB

  return(var.df) #return output
} # close function
